/* ============================================================
   I18N — manual Chinese/English switch for Moonlit Tarot
   - The user switches language MANUALLY via the header toggle.
     No auto-detection: default is "zh", choice persists in
     localStorage ("moonlit_lang").
   - Static HTML: data-i18n="key" (textContent),
     data-i18n-ph="key" (placeholder), data-i18n-html="key"
     (innerHTML), data-i18n-aria="key" (aria-label),
     data-i18n-title="key" (title attribute).
   - Dynamic JS strings: t("key") or t("key", {n: 3}).
   - Dictionaries are generated by tools/build-i18n.js into
     js/i18n-dict.js (sources: tools/i18n/*.json). Never edit
     i18n-dict.js by hand.
   - Card names/meanings: cardDisplayName() and cardMeaning()
     pick the language-appropriate variant from the shared
     card data (CARD_NAMES_ZH, upright_en/reversed_en).
   ============================================================ */

const I18N_DICT = { zh: {}, en: {} };

function getLang() {
  try {
    return localStorage.getItem("moonlit_lang") === "en" ? "en" : "zh";
  } catch (e) {
    return "zh";
  }
}

function t(key, vars) {
  const lang = getLang();
  const dict = I18N_DICT[lang] || {};
  let s = dict[key] !== undefined ? dict[key]
        : (I18N_DICT.zh[key] !== undefined ? I18N_DICT.zh[key] : key);
  if (vars) {
    s = String(s);
    for (const k of Object.keys(vars)) {
      s = s.split("{" + k + "}").join(String(vars[k]));
    }
  }
  return s;
}

function has(key) {
  const lang = getLang();
  return (I18N_DICT[lang] && I18N_DICT[lang][key] !== undefined)
      || I18N_DICT.zh[key] !== undefined;
}

function applyI18n() {
  const lang = getLang();
  document.documentElement.setAttribute("lang", lang === "en" ? "en" : "zh-CN");

  // If the dictionary failed to load (e.g. not built yet), leave the
  // original Chinese HTML untouched instead of stamping keys everywhere.
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const k = el.getAttribute("data-i18n");
    if (has(k)) el.textContent = t(k);
  });
  document.querySelectorAll("[data-i18n-ph]").forEach((el) => {
    const k = el.getAttribute("data-i18n-ph");
    if (has(k)) el.setAttribute("placeholder", t(k));
  });
  document.querySelectorAll("[data-i18n-html]").forEach((el) => {
    const k = el.getAttribute("data-i18n-html");
    if (has(k)) el.innerHTML = t(k);
  });
  document.querySelectorAll("[data-i18n-aria]").forEach((el) => {
    const k = el.getAttribute("data-i18n-aria");
    if (has(k)) el.setAttribute("aria-label", t(k));
  });
  document.querySelectorAll("[data-i18n-title]").forEach((el) => {
    const k = el.getAttribute("data-i18n-title");
    if (has(k)) el.setAttribute("title", t(k));
  });

  if (has("html.meta.title")) document.title = t("html.meta.title");
  const metaDesc = document.querySelector('meta[name="description"]');
  if (metaDesc && has("html.meta.description")) {
    metaDesc.setAttribute("content", t("html.meta.description"));
  }

  const btn = document.getElementById("lang-toggle");
  if (btn) btn.textContent = lang === "en" ? "中文" : "EN";

  document.dispatchEvent(new CustomEvent("moonlit-lang-change", { detail: { lang } }));
}

function setLang(lang) {
  const v = lang === "en" ? "en" : "zh";
  try {
    localStorage.setItem("moonlit_lang", v);
  } catch (e) {}
  applyI18n();
}

// Card display name: English in EN mode, Chinese in ZH mode.
// Delegates to zhCardName (card-names-zh.js), which is language-aware.
function cardDisplayName(card) {
  if (!card) return "";
  if (typeof zhCardName === "function") return zhCardName(card);
  if (typeof CARD_ZH_NAME !== "undefined" && CARD_ZH_NAME[card.id]) return CARD_ZH_NAME[card.id];
  return card.name || "";
}

// Card meaning keywords: upright_en / reversed_en in EN mode.
function cardMeaning(card, orient) {
  if (getLang() === "en" && card[orient + "_en"]) return card[orient + "_en"];
  return card[orient];
}

document.addEventListener("DOMContentLoaded", applyI18n);

// Header language toggle: manual switch, persists the choice.
document.addEventListener("DOMContentLoaded", () => {
  const btn = document.getElementById("lang-toggle");
  // Guard against double-binding (e.g. if DOMContentLoaded ever fires twice,
  // two handlers would toggle twice = no-op).
  if (btn && !btn.dataset.langBound) {
    btn.dataset.langBound = "1";
    btn.addEventListener("click", () => {
      setLang(getLang() === "en" ? "zh" : "en");
    });
  }
});
