// Merges tools/i18n/*.json into frontend/js/i18n-dict.js.
// Usage: node tools/build-i18n.js
const fs = require("fs");
const path = require("path");

const dir = path.join(__dirname, "i18n");
const zh = {};
const en = {};

for (const f of fs.readdirSync(dir)) {
  if (!f.endsWith(".json")) continue;
  const data = JSON.parse(fs.readFileSync(path.join(dir, f), "utf8"));
  for (const [k, v] of Object.entries(data)) {
    if (zh[k] !== undefined) {
      console.warn("DUPLICATE KEY: " + k + " (in " + f + ")");
      process.exitCode = 1;
    }
    if (typeof v.zh !== "string" || typeof v.en !== "string") {
      console.warn("BAD ENTRY (need {zh,en} strings): " + k + " (in " + f + ")");
      process.exitCode = 1;
      continue;
    }
    zh[k] = v.zh;
    en[k] = v.en;
  }
}

const out =
  "/* Generated by tools/build-i18n.js — do not edit by hand. Sources: tools/i18n/*.json */\n" +
  "Object.assign(I18N_DICT.zh, " + JSON.stringify(zh, null, 2) + ");\n" +
  "Object.assign(I18N_DICT.en, " + JSON.stringify(en, null, 2) + ");\n";

fs.writeFileSync(path.join(__dirname, "..", "frontend", "js", "i18n-dict.js"), out);
console.log("wrote frontend/js/i18n-dict.js: " + Object.keys(zh).length + " keys");
